### ISSUE TITLE
Pairing with Wii balance board?

### ISSUE THREAD

**Issue by tobiasbp** [madhephaestus/EspWii#1]
I'm a bit confused as to the purpose of this project. I'm looking for a way to pair a Wii balance board with the ESP32. Is there a library for using Wii controllers with the ESP32?

**Comment by madhephaestus** [comment]
This library is for hosting an i2c Wii accessory device,  supported by [WiiChuck](https://github.com/madhephaestus/WiiChuck), as a UDP server. There is also a client in the library for connecting to that server. It lets you plug any Wii accessoryinto one ESP32, then use that accessory on a different ESP32 over the infrastructure WIFI. The balance board is a Bluetooth device and not supported by WiiChuck.
